package com.mobdeve.caretracker

object MyFirestoreReferences {
    const val USERS_COLLECTION = "Users"
    const val PATIENT_COLLECTION = "Patients"
    const val NAME_FIELD = "Name"
    const val PATIENTNAME_FIELD = "patientName"
    const val PATIENTAGE_FIELD = "patientAge"
    const val PATIENTROOM_FIELD = "patientRoom"
    const val PATIENTLIST_FIELD = "patientList"
    const val PATIENTBIRTHDATE_FIELD = "patientBirthdate"
    const val PATIENTCIVILSTATUS_FIELD = "patientCivilStatus"
    const val PATIENTECN_FIELD = "patientECN"
    const val PATIENTECNO_FIELD = "patientECNo"
    const val PATIENTEMAIL_FIELD = "patientEmail"
    const val PATIENTMOBILENO_FIELD = "patientMobileno"
    const val PATIENTNATIONALITY_FIELD = "patientNationality"
    const val PATIENTRELIGION_FIELD = "patientReligion"
    const val PATIENTSEX_FIELD = "patientSex"

    const val PASSWORD_FIELD = "password"
    const val EMAIL_FIELD = "email"
    const val BOOKMARKS_FIELD = "Bookmarked"
    const val BIRTHDATE_FIELD = "birthdate"
    const val DESTINATIONS_COLLECTION = "Destinations"
    const val DESTNAME_FIELD = "destName"
    const val DESTIMAGE_FIELD = "destImage"
    const val DESTDESCRIPTION_FIELD = "destDescription"
    const val DESTCITY_FIELD = "destCity"
    const val DESTCATEGORY_FIELD = "destCategory"
    const val BOOKMARKAMOUNT_FIELD = "numOfBookmarks"
    const val LATITUDE_FIELD = "latitude"
    const val LONGITUDE_FIELD = "longitude"
}